require:
  - rubocop-rails

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true
  Details: 'Add `# frozen_string_literal: true` to the top of the file. Frozen string
    literals will become the default in a future Ruby version, and we want to make
    sure we''re ready.'

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
